env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  linebreak-style: 
    - error
    - windows
  no-console: off
  import/extensions: off
  max-len: 
    - error
    - 
      code: 150
  no-unused-vars: 
    - error
    - 
      argsIgnorePattern: '^_'
settings:
    import/resolver: 
      node:
        extensions: ['.js', '.ts', '.tsx']
